# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 562)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 80, 271, 71))
        self.label.setStyleSheet("font: 18pt \"黑体\";\n"
"")
        self.label.setScaledContents(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 360, 81, 41))
        self.pushButton.setStyleSheet("background-color: rgb(102, 240, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 360, 81, 41))
        self.pushButton_2.setStyleSheet("\n"
"background-color: rgb(146, 184, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 360, 81, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(198, 255, 251);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 360, 81, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(16, 255, 36);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "多功能识别系统"))
        self.pushButton.setText(_translate("Form", "人脸识别"))
        self.pushButton_2.setText(_translate("Form", "手势识别"))
        self.pushButton_3.setText(_translate("Form", "车牌识别"))
        self.pushButton_4.setText(_translate("Form", "退出"))
